proposed structure
mesoform/terraform-infrastructure-modules pull request #23
Opened 2020-11-11 02:24 UTC by dgavrischuk

2020-11-11 18:19 UTC, gbmeuk commented
@dgavrischuk, can you merge master into this branch.

2020-11-11 20:23 UTC, dgavrischuk commented
Done

> 11 лист. 2020 р. о 20:19 Gareth Brown <notifications@github.com> написав(ла):
> 
> 
> @dgavrischuk <https://github.com/dgavrischuk>, can you merge master into this branch.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/mesoform/terraform-infrastructure-modules/pull/23#issuecomment-725582826>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ARAXHYYQQPADSH5BEYY5GBTSPLIU7ANCNFSM4TRNCTYQ>.
>

2020-11-27 14:23 UTC, AlexBMes requested changes
Update the main mcp directory to match this structure

2020-12-02 19:02 UTC, gbmeuk reviewed
I presume some of these test files were actually supposed to be updates to the main module?￼

2020-12-02 19:02 UTC, gbmeuk commented on tests/mcp_structure_test/mcp/gcp_ae_locals.tf
> +locals {
Why is there code in the tests directory like this? Won't it override the real code in the module we're trying to test?

2020-12-06 20:10 UTC, gbmeuk requested changes
see comments

2020-12-11 10:09 UTC, AlexBMes submitted a review, later dismissed

2020-12-11 12:58 UTC, gbmeuk commented
There was an HTTP path in one of the Kubernetes adapters that was defaulting on the platform to "/" and was shown as changing on every run as a result.
@AlexBMes @dgavrischuk

2020-12-11 14:58 UTC, gbmeuk approved these changes

2020-12-11 14:58 UTC, merged