gcp secure instances
mesoform/terraform-infrastructure-modules pull request #42
Opened 2021-06-24 09:02 UTC by AlexBMes

Using specs for confidential vm creates: persistent disk, instance template and managed instance group for listed zones

2021-06-26 20:59 UTC, gbmeuk requested changes
I'm not sure how much value we're adding by having a module for the disks I realise that we will be able to apply the guest os features, it's just that, as you  proved, we don't currently need to use it and it will probably be natively available soon.

I also think that we can go with a single instance template and instance where we have a 'security level' value which configures them to an agreed standard. Then have a secure swarm composite module which utilises it. 

Let's discuss on Monday

2021-07-13 14:48 UTC, AlexBMes commented on gcp/secure_swarm_node/locals.tf
> +  green_instance_template = lookup(var.blue_instance_template, "security_level", null) == null ? merge(
Yes they were the same accidentally, have updated the green to use `var.green_instance_template`. Had also forgotten to implement these variables so have updated the `secure_instance_template_blue/green` modules to use the local variables

2021-07-13 14:48 UTC, AlexBMes commented on gcp/secure_swarm_node/main.tf
> +  experiments = [module_variable_optional_attrs]
Updated the documentation and minimum version to v0.14.0

2021-07-13 20:05 UTC, gbmeuk approved these changes
Approved but @danperezsan please review as well so as to use for the root module creation for client

2021-07-14 15:07 UTC, danperezsan approved these changes

2021-07-14 15:25 UTC, merged